import type { GenerateReadmeInput } from "@/features/readme/schemas/generate-readme";

function deriveTitle(description: string, stack: string) {
  const firstLine =
    description
      .split(/\r?\n/)
      .map((line) => line.trim())
      .find((line) => line.length > 0) ?? `${stack} Project`;

  const cleaned = firstLine
    .replace(/^#+\s*/, "")
    .replace(/^["'`]+|["'`]+$/g, "")
    .slice(0, 80);

  return cleaned || `${stack} Project`;
}

function excerpt(description: string, max = 280) {
  const compact = description.replace(/\s+/g, " ").trim();
  if (compact.length <= max) return compact;
  return `${compact.slice(0, max).trim()}…`;
}

function installBlock(stack: string) {
  switch (stack) {
    case "Python":
      return `\`\`\`bash
python -m venv .venv
source .venv/bin/activate  # Windows: .venv\\Scripts\\activate
pip install -r requirements.txt
python main.py
\`\`\``;
    case "Rust":
      return `\`\`\`bash
cargo build --release
cargo run
\`\`\``;
    case "Go":
      return `\`\`\`bash
go mod tidy
go run ./cmd/app
\`\`\``;
    case "Node.js":
      return `\`\`\`bash
npm install
npm start
\`\`\``;
    default:
      return `\`\`\`bash
npm install
npm run dev
\`\`\``;
  }
}

/**
 * Local mock README used when OPENAI_API_KEY is missing or a placeholder.
 * Lets us exercise UI + Job persistence without a live provider.
 */
export function buildMockReadme(input: GenerateReadmeInput) {
  const title = deriveTitle(input.description, input.stack);
  const summary = excerpt(input.description);
  const year = new Date().getFullYear();

  return `# ${title}

![Status](https://img.shields.io/badge/status-mock%20preview-blue)
![Stack](https://img.shields.io/badge/stack-${encodeURIComponent(input.stack).replace(/%20/g, "%20")}-informational)
![CodePilot](https://img.shields.io/badge/CodePilot-AI-black)

> Generated locally in **mock mode** (no OpenAI key configured). Swap in a real \`OPENAI_API_KEY\` for live model output.

## Overview

${summary}

This README was synthesized from your project description and the selected **${input.stack}** stack so you can validate the CodePilot UI, API, and database job flow end-to-end.

## Features

- Clean, developer-centric documentation structure
- Stack-aware getting started commands for **${input.stack}**
- Ready-to-copy Markdown for GitHub
- Persisted as a CodePilot \`README\` job with status \`SUCCEEDED\`

## Tech Stack

| Layer | Choice |
| --- | --- |
| Primary stack | ${input.stack} |
| Docs generator | CodePilot AI (mock) |
| Persistence | PostgreSQL + Prisma Job |

## Getting Started

### Prerequisites

- Runtime tooling for **${input.stack}**
- Git
- A package manager / build tool for your ecosystem

### Install & run

${installBlock(input.stack)}

## Usage

1. Open the project root.
2. Configure environment variables as needed.
3. Run the development command above.
4. Iterate on features and regenerate docs from CodePilot when ready.

## Project Structure

\`\`\`text
.
├── src/                 # Application source
├── docs/                # Extra documentation (optional)
├── tests/               # Automated tests
├── README.md            # You are here
└── package.json / Cargo.toml / pyproject.toml
\`\`\`

## Example Context Captured

\`\`\`text
${input.description.trim().slice(0, 1200)}
\`\`\`

## Contributing

Pull requests are welcome. For major changes, open an issue first to discuss what you would like to change.

## License

MIT © ${year} — generated by CodePilot AI (mock mode)
`;
}
